### ISSUE TITLE
Add an Image Underlay obj for the Web Interface

### ISSUE THREAD

**Issue by chriswmackey** [chriswmackey/BattleOfTheBldgs_Mockup#6]
@gouldingken ,
If you can remind me what the maximum image size is, I can ensure that I export an underlay with these properties.

**Comment by gouldingken** [comment]
2048x2048

Thanks

**Comment by gouldingken** [comment]
Also, I think we should go with a dark background to make the colored buildings stand out a little more, so ideally we'd have a dark-style basemap too.

**Comment by chriswmackey** [comment]
Thanks @gouldingken ,
I'll add the image when I get the chance and I agree with the dark background.

**Comment by chriswmackey** [comment]
Addressed via https://github.com/chriswmackey/BattleOfTheBldgs_Mockup/commit/59a48ba441d9d393d9e62843421647c7f315a854
